#!/bin/bash

mount -t devtmpfs dev       dev
mount -t devpts   dev/pts   dev/pts
mount -t proc     proc      proc
mount -t sysfs    sys       sys

ln -svf proc/self/fd    dev/fd
ln -svf proc/self/fd/0  dev/stdin
ln -svf proc/self/fd/1  dev/stdout
ln -svf proc/self/fd/2  dev/stderr

[ $$ -eq 1 ] && ! 2>/dev/null <0 && exec 0<>/dev/console 1>&0 2>&1
[ $$ -eq 1 ] && exec <>/dev/$(sed '$s@.*/@@' /sys/class/tty/console/active) 2>&1

echo 0 99999 > /proc/sys/net/ipv4/ping_group_range

# setup networking
# ifconfig lo 127.0.0.1
# ifconfig wlan0 192.168.6.234
# route add default gw 192.168.4.1
# timeout 2 sntp -sq 192.168.4.1
# sntp -sq time.google.com

# Run package scripts (if any)
for i in $(ls -1 /etc/rc 2>/dev/null | sort); do
    . /etc/rc/"$i"
done
echo 3 > /proc/sys/kernel/printk

echo "Running as PID $$"
/bin/bash -l
reboot -f
