#!/bin/sh

# Colors (for colored output in scripts and functions, e.g., log, die, etc.)
end="\e[00m"
bla="${end}\e[1;30m"
red="${end}\e[1;31m"
gre="${end}\e[1;32m"
yel="${end}\e[1;33m"
blu="${end}\e[1;34m"
pur="${end}\e[1;35m"
cya="${end}\e[1;36m"
gra="${end}\e[1;37m"
whi="${end}\e[1;39m"

# Prompt colors (for colorizing the PS1 variable, etc.)
_bla="\[$bla\]"
_red="\[$red\]"
_gre="\[$gre\]"
_yel="\[$yel\]"
_blu="\[$blu\]"
_pur="\[$pur\]"
_cya="\[$cya\]"
_gra="\[$gra\]"
_whi="\[$whi\]"
_end="\[$end\]"

export PS1="${_red}root${_whi}@${_red}l${_whi}f${_red}s${_whi}-${_red}f${_whi}s${_blu} \w #${_end} "

export HOME=/home
export PATH=/bin:/sbin:/usr/bin:/usr/sbin

mountpoint -q proc || mount -t proc proc proc
mountpoint -q sys || mount -t sysfs sys sys
if ! mountpoint -q dev; then
  mount -t devtmpfs dev dev
  [ $$ -eq 1 ] && ! 2>/dev/null <0 && exec 0<>/dev/console 1>&0 2>&1
  for i in ,fd /0,stdin /1,stdout /2,stderr; do
    ln -sf /proc/self/fd${i/,*/} dev/${i/*,/}
  done
  mkdir -p dev/shm
  chmod +t dev/shm
fi
mountpoint -q dev/pts || { mkdir -p dev/pts && mount -t devpts dev/pts dev/pts;}

# TODO: figure out networking
echo 0 99999 > /proc/sys/net/ipv4/ping_group_range
ifconfig lo 127.0.0.1
#ifconfig wlan 192.168.6.234
#route add default gw 192.168.4.1
#[ "$(date +%s)" -lt 1000 ] && timeout 2 sntp -sq 192.168.4.1 # Ask host
#[ "$(date +%s)" -lt 10000000 ] && sntp -sq time.google.com

echo "Running as PID $$"
# If any packages eventually install scripts in /etc/rc, run 'em
for i in $(ls -1 /etc/rc 2>/dev/null | sort); do . /etc/rc/"$i"; done
echo 3 > /proc/sys/kernel/printk

echo "cat /sys/class/tty/console/active"
cat /sys/class/tty/console/active

exec <>/dev/$(sed '$s@.*/@@' /sys/class/tty/console/active) 2>&1 &&
/bin/sh &&
reboot -f & # if init ever exits, the kernel panics
sleep 5
