#!/bin/bash

# colors
end="\e[00m"
bla="\e[1;30m"
red="\e[1;31m"
gre="\e[1;32m"
yel="\e[1;33m"
blu="\e[1;34m"
pur="\e[1;35m"
cya="\e[1;36m"
gra="\e[1;37m"
whi="\e[1;39m"

# ps1 colors
_bla="\[$bla\]"
_red="\[$red\]"
_gre="\[$gre\]"
_yel="\[$yel\]"
_blu="\[$blu\]"
_pur="\[$pur\]"
_cya="\[$cya\]"
_gra="\[$gra\]"
_whi="\[$whi\]"
_end="\[$end\]"

user="${_red}r${_whi}o${_red}o${_whi}t${_red}"
host="${_whi}l${_red}f${_whi}s${_red}f${_whi}s"
path="${_blu}\w #${_end}"
export PS1="${user}@${host} ${path} "
unset user host path

export HOME=/home
export PATH=/bin:/sbin:/usr/bin:/usr/sbin
